baseURL = 'https://hkust-knowcomp.github.io/NGDB/'
languageCode = 'en-us'
title = 'AganticDB: Building Smart Databases as Agents'
theme = 'ananke'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true    